-- =============================================================================
-- Verification queries for 03_pudl_create.sql
-- Assumes 03_pudl_create.sql has already been run.
--
-- Commented out by default so running this whole file doesn't silently fire
-- a read query against either table. Uncomment what you want to run, or run
-- it directly in the SQL Editor.
-- =============================================================================

-- === Verification ===
-- SELECT * FROM PUDL_S3.pudl_eia_energy_sources LIMIT 10;
-- SELECT * FROM PUDL_S3.pudl_eia_yearly_generators LIMIT 10;
