-- =============================================================================
-- Verification / example queries for 06_common_crawl_index_create.sql
-- Assumes 06_common_crawl_index_create.sql has already been run.
--
-- Commented out by default so running this whole file doesn't silently fire
-- a read query against the table. Uncomment what you want to run, or run it
-- directly in the SQL Editor.
-- =============================================================================

-- === Verification ===
-- SELECT * FROM CC_INDEX_S3.common_crawl_index LIMIT 10;

-- === Example queries ===
-- Suggested demo query once loaded -- this is the kind of "needle in a huge
-- columnar haystack" federation query this dataset is good for. Reminder
-- (see the license caveat in the create script): this table gives you the
-- URL, WARC file offset, and metadata to go *find* a page's content inside a
-- WARC file -- it does not itself contain page text. Keep the demo scoped to
-- the index unless you've separately worked through the crawled-content
-- licensing question in parquet-csv-data-sources.md #6.
--   SELECT url, url_host_name, fetch_status, content_mime_type, warc_filename
--   FROM common_crawl_index
--   WHERE url_host_tld = 'gov'
--   LIMIT 25;
